name: Face Service Preview CI/CD

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [staging]
    paths:
      - "face-service/**"
      - ".github/workflows/face-service-preview-env.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    environment: preview
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/face-service
          registryUrl: ${{ secrets.BACKEND_REGISTRY_URL }}
          registryUsername: ${{ secrets.BACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKEND_REGISTRY_PASSWORD }}
          containerAppName: face-recognition-service
          resourceGroup: hadu_lms_test
          imageToBuild: hadulms.azurecr.io/face-recognition-service:${{ github.sha }}
